Vagrant.configure("2") do |config|
	config.vm.hostname = 'sparseimage-test'
	config.vm.box = 'hashicorp/precise64'
	config.vm.network :private_network, ip: '172.16.42.10'

	config.sparseimage.add_image do |image|
		image.image_folder = './vagrant/image'
		image.volume_name = 'sparseimage_test'
		image.image_type = 'SPARSEIMAGE'
		image.image_fs = 'JHFS+'
		image.vm_mountpoint = '/srv/sparseimage_test'
		image.image_size = 512
		image.auto_unmount = false
	end
end
